#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xinit
Version  : 1.4.1
Release  : 18
URL      : https://xorg.freedesktop.org/releases/individual/app/xinit-1.4.1.tar.gz
Source0  : https://xorg.freedesktop.org/releases/individual/app/xinit-1.4.1.tar.gz
Source99 : https://xorg.freedesktop.org/releases/individual/app/xinit-1.4.1.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xinit-bin = %{version}-%{release}
Requires: xinit-data = %{version}-%{release}
Requires: xinit-license = %{version}-%{release}
Requires: xinit-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
Patch1: 0001-Provide-stateless-approach-to-startx-for-GNOME-XFCE.patch

%description
The xinit program is used to start the X Window System server and a first
client program on systems that are not using a display manager such as xdm.

%package bin
Summary: bin components for the xinit package.
Group: Binaries
Requires: xinit-data = %{version}-%{release}
Requires: xinit-license = %{version}-%{release}

%description bin
bin components for the xinit package.


%package data
Summary: data components for the xinit package.
Group: Data

%description data
data components for the xinit package.


%package license
Summary: license components for the xinit package.
Group: Default

%description license
license components for the xinit package.


%package man
Summary: man components for the xinit package.
Group: Default

%description man
man components for the xinit package.


%prep
%setup -q -n xinit-1.4.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557106008
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --with-xterm=xfce4-terminal \
--with-xinitdir=/usr/share/defaults/xinit
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557106008
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xinit
cp COPYING %{buildroot}/usr/share/package-licenses/xinit/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/startx
/usr/bin/xinit

%files data
%defattr(-,root,root,-)
/usr/share/defaults/xinit/xinitrc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xinit/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/startx.1
/usr/share/man/man1/xinit.1
